# -*- coding: utf-8 -*-
"""crop recommendation system.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cA96iQxmMuEiir-9KR08ejoUk6ZX8uUx
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import pickle

def predict(N, P, K, temperature, humidity, ph, rainfall):

    df = pd.read_csv('Crop_recommendation.csv')
    df

    df.shape

    df.info()

    df.isnull().sum()

    df['label'].unique()

    df['label'].value_counts()

    crop_summary = pd.pivot_table(df, index = ['label'], aggfunc = 'mean')
    crop_summary


    X = df.drop('label', axis=1)
    y = df['label']

    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

    from sklearn.ensemble import RandomForestClassifier

    model_2 = RandomForestClassifier()

    model_2.fit(X_train, y_train)

    from sklearn.metrics import accuracy_score

    y_pred_2 = model_2.predict(X_test)

  
    accuracy_2 = accuracy_score(y_pred_2, y_test)

    accuracy_2

    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test, y_pred_2)

    plt.figure(figsize=(15,15))
    plt.ylabel('Actual Values')
    plt.xlabel('Predicted Values')
    plt.show()
    pickle.dump(model_2 , open('mysaved_mdrecommen_pickle.pkl','wb'))
    X1_test=np.array([N, P, K, temperature, humidity, ph, rainfall])
    X1_test=X1_test.reshape((1,-1))
    return model_2.predict(X1_test)[0]

